INSERT INTO Lump(game, index_h, index_d, name, stage) VALUES
    ('r1', '0000',   0, 'ENTITIES',                       4),
    ('r1', '0001',   1, 'PLANES',                         3),  -- TODO: Portal Planes
    ('r1', '0002',   2, 'TEXTURE_DATA',                   4),
    ('r1', '0003',   3, 'VERTICES',                       4),
    ('r1', '000E',  14, 'MODELS',                         4),
    ('r1', '0018',  24, 'ENTITY_PARTITIONS',              4),
    ('r1', '001D',  29, 'PHYSICS_COLLIDE',                1),
    ('r1', '001E',  30, 'VERTEX_NORMALS',                 4),
    ('r1', '0023',  35, 'GAME_LUMP',                      3),
    ('r1', '0024',  36, 'LEAF_WATER_DATA',                0),
    ('r1', '0028',  40, 'PAKFILE',                        0),
    ('r1', '002A',  42, 'CUBEMAPS',                       0),
    ('r1', '002B',  43, 'TEXTURE_DATA_STRING_DATA',       4),
    ('r1', '002C',  44, 'TEXTURE_DATA_STRING_TABLE',      4),
    ('r1', '0036',  54, 'WORLD_LIGHTS',                   1),
    ('r1', '003E',  62, 'PHYSICS_LEVEL',                  0),
    ('r1', '0042',  66, 'TRICOLL_TRIANGLES',              0),
    ('r1', '0044',  68, 'TRICOLL_NODES',                  0),
    ('r1', '0045',  69, 'TRICOLL_HEADERS',                0),
    ('r1', '0046',  70, 'PHYSICS_TRIANGLES',              0),
    ('r1', '0047',  71, 'VERTEX_UNLIT',                   4),
    ('r1', '0048',  72, 'VERTEX_LIT_FLAT',                4),
    ('r1', '0049',  73, 'VERTEX_LIT_BUMP',                4),
    ('r1', '004A',  74, 'VERTEX_UNLIT_TS',                4),
    ('r1', '004B',  75, 'VERTEX_BLINN_PHONG',             4),
    ('r1', '004F',  79, 'MESH_INDICES',                   4),
    ('r1', '0050',  80, 'MESHES',                         3),  -- merging & splitting could be better
    ('r1', '0051',  81, 'MESH_BOUNDS',                    4),
    ('r1', '0052',  82, 'MATERIAL_SORTS',                 4),
    ('r1', '0053',  83, 'LIGHTMAP_HEADERS',               1),
    ('r1', '0055',  85, 'CM_GRID',                        3),  -- TODO: Portal Planes
    ('r1', '0056',  86, 'CM_GRID_CELLS',                  4),
    ('r1', '0057',  87, 'CM_GEO_SETS',                    3),  -- grouping could be better
    ('r1', '0058',  88, 'CM_GEO_SET_BOUNDS',              3),  -- always axis-aligned
    ('r1', '0059',  89, 'CM_PRIMITIVES',                  0),
    ('r1', '005A',  90, 'CM_PRIMITIVE_BOUNDS',            0),
    ('r1', '005B',  91, 'CM_UNIQUE_CONTENTS',             3),
    ('r1', '005C',  92, 'CM_BRUSHES',                     3),
    ('r1', '005D',  93, 'CM_BRUSH_SIDE_PLANE_OFFSETS',    3),
    ('r1', '005E',  94, 'CM_BRUSH_SIDE_PROPERTIES',       3),
    ('r1', '005F',  95, 'CM_BRUSH_SIDE_TEXTURE_VECTORS',  3),
    ('r1', '0060',  96, 'TRICOLL_BEVEL_STARTS',           0),
    ('r1', '0061',  97, 'TRICOLL_BEVEL_INDICES',          0),
    ('r1', '0062',  98, 'LIGHTMAP_DATA_SKY',              1),
    ('r1', '0063',  99, 'CSM_AABB_NODES',                 1),
    ('r1', '0064', 100, 'CSM_OBJ_REFERENCES',             1),
    ('r1', '0065', 101, 'LIGHTPROBES',                    0),
    ('r1', '0066', 102, 'STATIC_PROP_LIGHTPROBE_INDICES', 0),
    ('r1', '0067', 103, 'LIGHTPROBE_TREE',                0),
    ('r1', '0068', 104, 'LIGHTPROBE_REFERENCES',          0),
    ('r1', '0069', 105, 'LIGHTMAP_DATA_REAL_TIME_LIGHTS', 0),
    ('r1', '006A', 106, 'CELL_BSP_NODES',                 2),
    ('r1', '006B', 107, 'CELLS',                          2),
    ('r1', '006C', 108, 'PORTALS',                        2),
    ('r1', '006D', 109, 'PORTAL_VERTICES',                2),
    ('r1', '006E', 110, 'PORTAL_EDGES',                   2),
    ('r1', '006F', 111, 'PORTAL_VERTEX_EDGES',            2),
    ('r1', '0070', 112, 'PORTAL_VERTEX_REFERENCES',       2),
    ('r1', '0071', 113, 'PORTAL_EDGE_REFERENCES',         2),
    ('r1', '0072', 114, 'PORTAL_EDGE_INTERSECT_EDGE',     2),
    ('r1', '0073', 115, 'PORTAL_EDGE_INTERSECT_VERTEX',   2),
    ('r1', '0074', 116, 'PORTAL_EDGE_INTERSECT_HEADER',   2),
    ('r1', '0075', 117, 'OCCLUSION_MESH_VERTICES',        0),
    ('r1', '0076', 118, 'OCCLUSION_MESH_INDICES',         0),
    ('r1', '0077', 119, 'CELL_AABB_NODES',                3),
    ('r1', '0078', 120, 'OBJ_REFERENCES',                 3),
    ('r1', '0079', 121, 'OBJ_REFERENCE_BOUNDS',           3),
    ('r1', '007B', 123, 'LEVEL_INFO',                     3),
    ('r1', '007C', 124, 'SHADOW_MESH_OPAQUE_VERTICES',    0),
    ('r1', '007D', 125, 'SHADOW_MESH_ALPHA_VERTICES',     0),
    ('r1', '007E', 126, 'SHADOW_MESH_INDICES',            0),
    ('r1', '007F', 127, 'SHADOW_MESHES',                  0);


INSERT INTO LumpSystem(game, system, lump) VALUES
    -- Brushes
    ('r1', 'Brushes', 'CM_BRUSHES'),
    ('r1', 'Brushes', 'CM_BRUSH_SIDE_PLANE_OFFSETS'),
    ('r1', 'Brushes', 'CM_BRUSH_SIDE_PROPERTIES'),
    ('r1', 'Brushes', 'CM_BRUSH_SIDE_TEXTURE_VECTORS'),
    ('r1', 'Brushes', 'PLANES'),
    ('r1', 'Brushes', 'TEXTURE_DATA'),
    -- Cascading Shadow Maps
    ('r1', 'Cascading Shadow Maps', 'CSM_AABB_NODES'),
    ('r1', 'Cascading Shadow Maps', 'CSM_OBJ_REFERENCES'),
    -- Cell-Portal BSP Tree
    ('r1', 'Cell-Portal BSP Tree', 'CELLS'),
    ('r1', 'Cell-Portal BSP Tree', 'CELL_BSP_NODES'),
    ('r1', 'Cell-Portal BSP Tree', 'LEAF_WATER_DATA'),
    ('r1', 'Cell-Portal BSP Tree', 'PLANES'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTALS'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_EDGES'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_INTERSECT_EDGE'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_INTERSECT_HEADER'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_INTERSECT_VERTEX'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_REFERENCES'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_VERTEX_EDGES'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_VERTEX_REFERENCES'),
    ('r1', 'Cell-Portal BSP Tree', 'PORTAL_VERTICES'),
    ('r1', 'Cell-Portal BSP Tree', 'TEXTURE_DATA'),
    -- ClipModel
    ('r1', 'ClipModel', 'CM_GEO_SETS'),
    ('r1', 'ClipModel', 'CM_GEO_SET_BOUNDS'),
    ('r1', 'ClipModel', 'CM_GRID'),
    ('r1', 'ClipModel', 'CM_GRID_CELLS'),
    ('r1', 'ClipModel', 'CM_PRIMITIVES'),
    ('r1', 'ClipModel', 'CM_PRIMITIVE_BOUNDS'),
    ('r1', 'ClipModel', 'CM_UNIQUE_CONTENTS'),
    -- Lightmaps
    ('r1', 'Lightmaps', 'LIGHTMAP_DATA_REAL_TIME_LIGHTS'),
    ('r1', 'Lightmaps', 'LIGHTMAP_DATA_SKY'),
    ('r1', 'Lightmaps', 'LIGHTMAP_HEADERS'),
    -- LightProbes
    ('r1', 'Lightprobes', 'LIGHTPROBES'),
    ('r1', 'Lightprobes', 'LIGHTPROBE_REFERENCES'),
    ('r1', 'Lightprobes', 'LIGHTPROBE_TREE'),
    ('r1', 'Lightprobes', 'STATIC_PROP_LIGHTPROBE_INDICES'),
    -- Models
    ('r1', 'Models', 'MATERIAL_SORTS'),
    ('r1', 'Models', 'MESHES'),
    ('r1', 'Models', 'MESH_BOUNDS'),
    ('r1', 'Models', 'MESH_INDICES'),
    ('r1', 'Models', 'MODELS'),
    ('r1', 'Models', 'TEXTURE_DATA'),
    ('r1', 'Models', 'TEXTURE_DATA_STRING_DATA'),
    ('r1', 'Models', 'TEXTURE_DATA_STRING_TABLE'),
    ('r1', 'Models', 'VERTEX_BLINN_PHONG'),
    ('r1', 'Models', 'VERTEX_LIT_BUMP'),
    ('r1', 'Models', 'VERTEX_LIT_FLAT'),
    ('r1', 'Models', 'VERTEX_NORMALS'),
    ('r1', 'Models', 'VERTEX_UNLIT'),
    ('r1', 'Models', 'VERTEX_UNLIT_TS'),
    ('r1', 'Models', 'VERTICES'),
    -- ObjReferences
    ('r1', 'ObjReferences', 'CELL_AABB_NODES'),
    ('r1', 'ObjReferences', 'OBJ_REFERENCES'),
    ('r1', 'ObjReferences', 'OBJ_REFERENCE_BOUNDS'),
    -- ShadowMeshes
    ('r1', 'ShadowMeshes', 'MATERIAL_SORTS'),
    ('r1', 'ShadowMeshes', 'SHADOW_MESHES'),
    ('r1', 'ShadowMeshes', 'SHADOW_MESH_ALPHA_VERTICES'),
    ('r1', 'ShadowMeshes', 'SHADOW_MESH_INDICES'),
    ('r1', 'ShadowMeshes', 'SHADOW_MESH_OPAQUE_VERTICES'),
    -- TriColl
    ('r1', 'TriColl', 'TRICOLL_BEVEL_INDICES'),
    ('r1', 'TriColl', 'TRICOLL_BEVEL_STARTS'),
    ('r1', 'TriColl', 'TRICOLL_HEADERS'),
    ('r1', 'TriColl', 'TRICOLL_NODES'),
    ('r1', 'TriColl', 'TRICOLL_TRIANGLES'),
    -- Worldlights
    ('r1', 'WorldLights', 'WORLD_LIGHTS');
