INSERT INTO Lump(game, index_h, index_d, name, stage) VALUES
    ('r2', '0000',   0, 'ENTITIES',                       4),
    ('r2', '0001',   1, 'PLANES',                         3),  -- TODO: Portal Planes
    ('r2', '0002',   2, 'TEXTURE_DATA',                   4),
    ('r2', '0003',   3, 'VERTICES',                       4),
    ('r2', '0004',   4, 'LIGHTPROBE_PARENT_INFOS',        0),
    ('r2', '0005',   5, 'SHADOW_ENVIRONMENTS',            0),
    ('r2', '0006',   6, 'LIGHTPROBE_BSP_NODES',           0),
    ('r2', '0007',   7, 'LIGHTPROBE_BSP_REF_IDS',         0),
    ('r2', '000E',  14, 'MODELS',                         4),
    ('r2', '0018',  24, 'ENTITY_PARTITIONS',              4),
    ('r2', '001D',  29, 'PHYSICS_COLLIDE',                0),
    ('r2', '001E',  30, 'VERTEX_NORMALS',                 4),
    ('r2', '0023',  35, 'GAME_LUMP',                      3),
    ('r2', '0024',  36, 'LEAF_WATER_DATA',                0),
    ('r2', '0028',  40, 'PAKFILE',                        0),
    ('r2', '002A',  42, 'CUBEMAPS',                       0),
    ('r2', '002B',  43, 'TEXTURE_DATA_STRING_DATA',       4),
    ('r2', '002C',  44, 'TEXTURE_DATA_STRING_TABLE',      4),
    ('r2', '0036',  54, 'WORLD_LIGHTS',                   1),
    ('r2', '0037',  55, 'WORLD_LIGHT_PARENT_INFOS',       0),
    ('r2', '0042',  66, 'TRICOLL_TRIANGLES',              0),
    ('r2', '0044',  68, 'TRICOLL_NODES',                  0),
    ('r2', '0045',  69, 'TRICOLL_HEADERS',                0),
    ('r2', '0047',  71, 'VERTEX_UNLIT',                   4),
    ('r2', '0048',  72, 'VERTEX_LIT_FLAT',                4),
    ('r2', '0049',  73, 'VERTEX_LIT_BUMP',                4),
    ('r2', '004A',  74, 'VERTEX_UNLIT_TS',                4),
    ('r2', '004B',  75, 'VERTEX_BLINN_PHONG',             4),
    ('r2', '004F',  79, 'MESH_INDICES',                   4),
    ('r2', '0050',  80, 'MESHES',                         3),  -- merging & splitting could be better
    ('r2', '0051',  81, 'MESH_BOUNDS',                    4),
    ('r2', '0052',  82, 'MATERIAL_SORTS',                 4),
    ('r2', '0053',  83, 'LIGHTMAP_HEADERS',               0),
    ('r2', '0055',  85, 'CM_GRID',                        3),  -- TODO: Portal Planes
    ('r2', '0056',  86, 'CM_GRID_CELLS',                  4),
    ('r2', '0057',  87, 'CM_GEO_SETS',                    3),  -- grouping could be better
    ('r2', '0058',  88, 'CM_GEO_SET_BOUNDS',              3),  -- always axis-aligned
    ('r2', '0059',  89, 'CM_PRIMITIVES',                  0),
    ('r2', '005A',  90, 'CM_PRIMITIVE_BOUNDS',            0),
    ('r2', '005B',  91, 'CM_UNIQUE_CONTENTS',             3),
    ('r2', '005C',  92, 'CM_BRUSHES',                     3),
    ('r2', '005D',  93, 'CM_BRUSH_SIDE_PLANE_OFFSETS',    3),
    ('r2', '005E',  94, 'CM_BRUSH_SIDE_PROPERTIES',       3),
    ('r2', '005F',  95, 'CM_BRUSH_SIDE_TEXTURE_VECTORS',  3),
    ('r2', '0060',  96, 'TRICOLL_BEVEL_STARTS',           0),
    ('r2', '0061',  97, 'TRICOLL_BEVEL_INDICES',          0),
    ('r2', '0062',  98, 'LIGHTMAP_DATA_SKY',              1),
    ('r2', '0063',  99, 'CSM_AABB_NODES',                 1),
    ('r2', '0064', 100, 'CSM_OBJ_REFERENCES',             1),
    ('r2', '0065', 101, 'LIGHTPROBES',                    0),
    ('r2', '0066', 102, 'STATIC_PROP_LIGHTPROBE_INDICES', 0),
    ('r2', '0067', 103, 'LIGHTPROBE_TREE',                0),
    ('r2', '0068', 104, 'LIGHTPROBE_REFERENCES',          0),
    ('r2', '0069', 105, 'LIGHTMAP_DATA_REAL_TIME_LIGHTS', 0),
    ('r2', '006A', 106, 'CELL_BSP_NODES',                 1),
    ('r2', '006B', 107, 'CELLS',                          1),
    ('r2', '006C', 108, 'PORTALS',                        0),
    ('r2', '006D', 109, 'PORTAL_VERTICES',                0),
    ('r2', '006E', 110, 'PORTAL_EDGES',                   0),
    ('r2', '006F', 111, 'PORTAL_VERTEX_EDGES',            0),
    ('r2', '0070', 112, 'PORTAL_VERTEX_REFERENCES',       0),
    ('r2', '0071', 113, 'PORTAL_EDGE_REFERENCES',         0),
    ('r2', '0072', 114, 'PORTAL_EDGE_INTERSECT_EDGE',     0),
    ('r2', '0073', 115, 'PORTAL_EDGE_INTERSECT_VERTEX',   0),
    ('r2', '0074', 116, 'PORTAL_EDGE_INTERSECT_HEADER',   0),
    ('r2', '0075', 117, 'OCCLUSION_MESH_VERTICES',        4),
    ('r2', '0076', 118, 'OCCLUSION_MESH_INDICES',         4),
    ('r2', '0077', 119, 'CELL_AABB_NODES',                3),  -- might need a revisit
    ('r2', '0078', 120, 'OBJ_REFERENCES',                 3),
    ('r2', '0079', 121, 'OBJ_REFERENCE_BOUNDS',           3),
    ('r2', '007A', 122, 'LIGHTMAP_DATA_RTL_PAGES',        0),
    ('r2', '007B', 123, 'LEVEL_INFO',                     3),
    ('r2', '007C', 124, 'SHADOW_MESH_OPAQUE_VERTICES',    0),
    ('r2', '007D', 125, 'SHADOW_MESH_ALPHA_VERTICES',     0),
    ('r2', '007E', 126, 'SHADOW_MESH_INDICES',            0),
    ('r2', '007F', 127, 'SHADOW_MESHES',                  0);


INSERT INTO LumpSystem(game, system, lump) VALUES
    -- Brushes
    ('r2', 'Brushes', 'CM_BRUSHES'),
    ('r2', 'Brushes', 'CM_BRUSH_SIDE_PLANE_OFFSETS'),
    ('r2', 'Brushes', 'CM_BRUSH_SIDE_PROPERTIES'),
    ('r2', 'Brushes', 'CM_BRUSH_SIDE_TEXTURE_VECTORS'),
    ('r2', 'Brushes', 'PLANES'),
    ('r2', 'Brushes', 'TEXTURE_DATA'),
    -- Cascading Shadow Maps
    ('r2', 'Cascading Shadow Maps', 'CSM_AABB_NODES'),
    ('r2', 'Cascading Shadow Maps', 'CSM_OBJ_REFERENCES'),
    -- Cell-Portal BSP Tree
    ('r2', 'Cell-Portal BSP Tree', 'CELLS'),
    ('r2', 'Cell-Portal BSP Tree', 'CELL_BSP_NODES'),
    ('r2', 'Cell-Portal BSP Tree', 'LEAF_WATER_DATA'),
    ('r2', 'Cell-Portal BSP Tree', 'PLANES'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTALS'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_EDGES'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_INTERSECT_EDGE'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_INTERSECT_HEADER'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_INTERSECT_VERTEX'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_EDGE_REFERENCES'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_VERTEX_EDGES'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_VERTEX_REFERENCES'),
    ('r2', 'Cell-Portal BSP Tree', 'PORTAL_VERTICES'),
    ('r2', 'Cell-Portal BSP Tree', 'TEXTURE_DATA'),
    -- ClipModel
    ('r2', 'ClipModel', 'CM_GEO_SETS'),
    ('r2', 'ClipModel', 'CM_GEO_SET_BOUNDS'),
    ('r2', 'ClipModel', 'CM_GRID'),
    ('r2', 'ClipModel', 'CM_GRID_CELLS'),
    ('r2', 'ClipModel', 'CM_PRIMITIVES'),
    ('r2', 'ClipModel', 'CM_PRIMITIVE_BOUNDS'),
    ('r2', 'ClipModel', 'CM_UNIQUE_CONTENTS'),
    -- Lightmaps
    ('r2', 'Lightmaps', 'LIGHTMAP_DATA_REAL_TIME_LIGHTS'),
    ('r2', 'Lightmaps', 'LIGHTMAP_DATA_RTL_PAGES'),
    ('r2', 'Lightmaps', 'LIGHTMAP_DATA_SKY'),
    ('r2', 'Lightmaps', 'LIGHTMAP_HEADERS'),
    -- LightProbes
    ('r2', 'Lightprobes', 'LIGHTPROBES'),
    ('r2', 'Lightprobes', 'LIGHTPROBE_BSP_NODES'),
    ('r2', 'Lightprobes', 'LIGHTPROBE_BSP_REF_IDS'),
    ('r2', 'Lightprobes', 'LIGHTPROBE_PARENT_INFOS'),
    ('r2', 'Lightprobes', 'LIGHTPROBE_REFERENCES'),
    ('r2', 'Lightprobes', 'LIGHTPROBE_TREE'),
    ('r2', 'Lightprobes', 'STATIC_PROP_LIGHTPROBE_INDICES'),
    -- Models
    ('r2', 'Models', 'MATERIAL_SORTS'),
    ('r2', 'Models', 'MESHES'),
    ('r2', 'Models', 'MESH_BOUNDS'),
    ('r2', 'Models', 'MESH_INDICES'),
    ('r2', 'Models', 'MODELS'),
    ('r2', 'Models', 'TEXTURE_DATA'),
    ('r2', 'Models', 'TEXTURE_DATA_STRING_DATA'),
    ('r2', 'Models', 'TEXTURE_DATA_STRING_TABLE'),
    ('r2', 'Models', 'VERTEX_BLINN_PHONG'),
    ('r2', 'Models', 'VERTEX_LIT_BUMP'),
    ('r2', 'Models', 'VERTEX_LIT_FLAT'),
    ('r2', 'Models', 'VERTEX_NORMALS'),
    ('r2', 'Models', 'VERTEX_UNLIT'),
    ('r2', 'Models', 'VERTEX_UNLIT_TS'),
    ('r2', 'Models', 'VERTICES'),
    -- ObjReferences
    ('r2', 'ObjReferences', 'CELL_AABB_NODES'),
    ('r2', 'ObjReferences', 'OBJ_REFERENCES'),
    ('r2', 'ObjReferences', 'OBJ_REFERENCE_BOUNDS'),
    -- ShadowMeshes
    ('r2', 'ShadowMeshes', 'MATERIAL_SORTS'),
    ('r2', 'ShadowMeshes', 'SHADOW_ENVIRONMENTS'),
    ('r2', 'ShadowMeshes', 'SHADOW_MESHES'),
    ('r2', 'ShadowMeshes', 'SHADOW_MESH_ALPHA_VERTICES'),
    ('r2', 'ShadowMeshes', 'SHADOW_MESH_INDICES'),
    ('r2', 'ShadowMeshes', 'SHADOW_MESH_OPAQUE_VERTICES'),
    -- TriColl
    ('r2', 'TriColl', 'TRICOLL_BEVEL_INDICES'),
    ('r2', 'TriColl', 'TRICOLL_BEVEL_STARTS'),
    ('r2', 'TriColl', 'TRICOLL_HEADERS'),
    ('r2', 'TriColl', 'TRICOLL_NODES'),
    ('r2', 'TriColl', 'TRICOLL_TRIANGLES'),
    -- Worldlights
    ('r2', 'WorldLights', 'WORLD_LIGHTS'),
    ('r2', 'WorldLights', 'WORLD_LIGHT_PARENT_INFOS');
